name: locally
description: This package helps developers create local notification in flutter, it extends the flutter local notification package and tries to make usage more simple and user friendly.
version: 0.0.1
homepage: https://github.com/samuelezedi/locally

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

